# -*- coding: utf-8 -*-
"""프로젝트(min).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11rHPzTGJ5Q8YS9eK1qkapQWsow3zL4KR

0. 데이터 준비하기 : [강수량 데이터](*https://data.kma.go.kr/data/grnd/selectAwsRltmList.do?pgmNo=56)
"""

!git clone https://github.com/Hardcodinglove/2022dataset

cd 2022dataset

"""1. 데이터 살펴보기

### 1-1. 전체 데이터 읽어오기
"""

import csv
data = csv.reader(open('raindata.csv', encoding='cp949'))

for row in data :
  print(row)

"""1-2. 원하는 지역 데이터의 인구수 살펴보기"""

import csv
data = csv.reader(open('raindata.csv', encoding='cp949'))
next(data)
for row in data :
  if row[1] == '영덕' : 
    print(row[2], row[-1])

"""1-3. 하루에 100mm 이상 온 날은?"""

import csv
data = csv.reader(open('raindata.csv', encoding='cp949'))
next(data)
rain = []
for row in data :
  if row[1] == '영덕' : 
    if float(row[-1]) > 100 : 
      print(row[2], row[-1])
    rain.append(float(row[-1]))
print(rain)

"""1-4. 데이터 시각화하기"""

# 지난 10년간, 강수량을 시각화해서 살펴보면?
import matplotlib.pyplot as plt
plt.plot(rain)
plt.show()
plt.boxplot(rain)
plt.show()

"""1-5. 비가 온 날(강수량 0 초과)만 확인하면?"""

import csv
data = csv.reader(open('raindata.csv'))
next(data)
rain2 = []
for row in data :
  if row[1] == '기상청' : 
    if float(row[-1]) > 0 : 
      print(row[2], row[-1])
      rain2.append(float(row[-1]))
print(rain2)

# 지난 10년간, 비가 온 날만 살펴보면?
import matplotlib.pyplot as plt
plt.plot(rain2)
plt.show()
plt.boxplot(rain2)
plt.show()
plt.hist(rain2, bins = 400)
plt.show()

# 지난 10년간, 비가 오지 않은 날과 온 날의 비율은?
plt.bar([0,1], [len(rain) - len(rain2), len(rain2)])
plt.show()

plt.pie([len(rain) - len(rain2), len(rain2)], autopct = '%.2f%%')
plt.show()